eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    url: jdbc:mysql://localhost:3306/students_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
application:
  config:
    courses-url: http://localhost:8222/api/v1/courses
management:
  tracing:
    sampling:
      probability: 1.0
